# Generated by Django 2.2.4 on 2019-08-25 14:31

from django.db import migrations, models
import django.db.models.deletion
import djirgha.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', djirgha.models.Punkt(name='a1', x=30, y=30)),
                ('a2', djirgha.models.Punkt(name='a2', x=414.0, y=30)),
                ('a3', djirgha.models.Punkt(name='a3', x=798, y=30)),
                ('a4', djirgha.models.Punkt(name='a4', x=798, y=414.0)),
                ('a5', djirgha.models.Punkt(name='a5', x=798, y=798)),
                ('a6', djirgha.models.Punkt(name='a6', x=414.0, y=798)),
                ('a7', djirgha.models.Punkt(name='a7', x=30, y=798)),
                ('a8', djirgha.models.Punkt(name='a8', x=30, y=414.0)),
                ('b1', djirgha.models.Punkt(name='b1', x=222.0, y=222.0)),
                ('b2', djirgha.models.Punkt(name='b2', x=414.0, y=222.0)),
                ('b3', djirgha.models.Punkt(name='b3', x=606.0, y=222.0)),
                ('b4', djirgha.models.Punkt(name='b4', x=606.0, y=414.0)),
                ('b5', djirgha.models.Punkt(name='b5', x=606.0, y=606.0)),
                ('b6', djirgha.models.Punkt(name='b6', x=414.0, y=606.0)),
                ('b7', djirgha.models.Punkt(name='b7', x=222.0, y=606.0)),
                ('b8', djirgha.models.Punkt(name='b8', x=222.0, y=414.0)),
                ('c1', djirgha.models.Punkt(name='c1', x=318.0, y=318.0)),
                ('c2', djirgha.models.Punkt(name='c2', x=510.0, y=318.0)),
                ('c3', djirgha.models.Punkt(name='c3', x=510.0, y=510.0)),
                ('c4', djirgha.models.Punkt(name='c4', x=318.0, y=510.0)),
                ('state', models.SmallIntegerField(default=1)),
                ('match', models.PositiveSmallIntegerField(default=0)),
                ('prev_turn', models.CharField(choices=[('a1', 'a1'), ('a2', 'a2'), ('a3', 'a3'), ('a4', 'a4'), ('a5', 'a5'), ('a6', 'a6'), ('a7', 'a7'), ('a8', 'a8'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('b5', 'b5'), ('b6', 'b6'), ('b7', 'b7'), ('b8', 'b8'), ('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4')], max_length=2, null=True)),
                ('black', models.PositiveSmallIntegerField(default=10)),
                ('white', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('old_state', models.SmallIntegerField()),
                ('new_state', models.SmallIntegerField()),
                ('punkt', models.CharField(choices=[('a1', 'a1'), ('a2', 'a2'), ('a3', 'a3'), ('a4', 'a4'), ('a5', 'a5'), ('a6', 'a6'), ('a7', 'a7'), ('a8', 'a8'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('b5', 'b5'), ('b6', 'b6'), ('b7', 'b7'), ('b8', 'b8'), ('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4')], max_length=2, null=True)),
                ('match', models.PositiveSmallIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='djirgha.Board')),
            ],
            options={
                'unique_together': {('board', 'number')},
            },
        ),
    ]
